//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeGenerator.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarcodeGenerator.Resources.Languages.CodeLang", typeof(CodeLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color:.
        /// </summary>
        internal static string BackgroundColor_Text {
            get {
                return ResourceManager.GetString("BackgroundColor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background opacity:.
        /// </summary>
        internal static string BackgroundOpacity_Text {
            get {
                return ResourceManager.GetString("BackgroundOpacity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode color:.
        /// </summary>
        internal static string BarcodeColor_Text {
            get {
                return ResourceManager.GetString("BarcodeColor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Generator.
        /// </summary>
        internal static string BarcodeGenerator_Text {
            get {
                return ResourceManager.GetString("BarcodeGenerator_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ClearCode_Text {
            get {
                return ResourceManager.GetString("ClearCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default format:.
        /// </summary>
        internal static string DefaultFormat_Text {
            get {
                return ResourceManager.GetString("DefaultFormat_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a format:.
        /// </summary>
        internal static string FormatCode_Text {
            get {
                return ResourceManager.GetString("FormatCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string GenerateCode_Text {
            get {
                return ResourceManager.GetString("GenerateCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language_Text {
            get {
                return ResourceManager.GetString("Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string SettingsReset_Text {
            get {
                return ResourceManager.GetString("SettingsReset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SettingsSave_Text {
            get {
                return ResourceManager.GetString("SettingsSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share_Text {
            get {
                return ResourceManager.GetString("Share_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to encode:.
        /// </summary>
        internal static string TextToEncode_Text {
            get {
                return ResourceManager.GetString("TextToEncode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        internal static string Theme_Text {
            get {
                return ResourceManager.GetString("Theme_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string ThemeDark_Text {
            get {
                return ResourceManager.GetString("ThemeDark_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string ThemeLight_Text {
            get {
                return ResourceManager.GetString("ThemeLight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string ThemeSystem_Text {
            get {
                return ResourceManager.GetString("ThemeSystem_Text", resourceCulture);
            }
        }
    }
}
