//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeGenerator.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarcodeGenerator.Resources.Languages.CodeLang", typeof(CodeLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About_Text {
            get {
                return ResourceManager.GetString("About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Translate was used for the translation of the text. This is not a guarantee that all translations are correct.
        ///The supporting languages are: Dutch, English, French, German, Italian, Portuguese and Spanish.
        ///
        ///You can always contact me for any corrections..
        /// </summary>
        internal static string AboutExplanation_Text {
            get {
                return ResourceManager.GetString("AboutExplanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string Agree_Text {
            get {
                return ResourceManager.GetString("Agree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All codes.
        /// </summary>
        internal static string AllCodes_Text {
            get {
                return ResourceManager.GetString("AllCodes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed characters:.
        /// </summary>
        internal static string AllowedChar_Text {
            get {
                return ResourceManager.GetString("AllowedChar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed:.
        /// </summary>
        internal static string AllowedCharNot_Text {
            get {
                return ResourceManager.GetString("AllowedCharNot_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color:.
        /// </summary>
        internal static string BackgroundColor_Text {
            get {
                return ResourceManager.GetString("BackgroundColor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background opacity:.
        /// </summary>
        internal static string BackgroundOpacity_Text {
            get {
                return ResourceManager.GetString("BackgroundOpacity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Generator.
        /// </summary>
        internal static string BarcodeGenerator_Text {
            get {
                return ResourceManager.GetString("BarcodeGenerator_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Scanner.
        /// </summary>
        internal static string BarcodeScanner_Text {
            get {
                return ResourceManager.GetString("BarcodeScanner_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ButtonClose_Text {
            get {
                return ResourceManager.GetString("ButtonClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen.
        /// </summary>
        internal static string ButtonListen_Text {
            get {
                return ResourceManager.GetString("ButtonListen_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string ButtonShare_Text {
            get {
                return ResourceManager.GetString("ButtonShare_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share text.
        /// </summary>
        internal static string ButtonShareText_Text {
            get {
                return ResourceManager.GetString("ButtonShareText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak.
        /// </summary>
        internal static string ButtonSpeak_Text {
            get {
                return ResourceManager.GetString("ButtonSpeak_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is wrong.
        ///The check digit has been corrected..
        /// </summary>
        internal static string CheckDigitError_Text {
            get {
                return ResourceManager.GetString("CheckDigitError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ClearCode_Text {
            get {
                return ResourceManager.GetString("ClearCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the application..
        /// </summary>
        internal static string CloseApplication_Text {
            get {
                return ResourceManager.GetString("CloseApplication_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code should be.
        /// </summary>
        internal static string CodeLengthPart1_Text {
            get {
                return ResourceManager.GetString("CodeLengthPart1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (without checksum digit) or.
        /// </summary>
        internal static string CodeLengthPart2_Text {
            get {
                return ResourceManager.GetString("CodeLengthPart2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digits long..
        /// </summary>
        internal static string CodeLengthPart3_Text {
            get {
                return ResourceManager.GetString("CodeLengthPart3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        internal static string Contact_Text {
            get {
                return ResourceManager.GetString("Contact_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Copyright_Text {
            get {
                return ResourceManager.GetString("Copyright_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default_Text {
            get {
                return ResourceManager.GetString("Default_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default format generator:.
        /// </summary>
        internal static string DefaultFormatGenerator_Text {
            get {
                return ResourceManager.GetString("DefaultFormatGenerator_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default format scanner:.
        /// </summary>
        internal static string DefaultFormatScanner_Text {
            get {
                return ResourceManager.GetString("DefaultFormatScanner_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate and scan various barcodes..
        /// </summary>
        internal static string Description_Text {
            get {
                return ResourceManager.GetString("Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disagree.
        /// </summary>
        internal static string Disagree_Text {
            get {
                return ResourceManager.GetString("Disagree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string Email_Text {
            get {
                return ResourceManager.GetString("Email_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle_Text {
            get {
                return ResourceManager.GetString("ErrorTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First number should be 0..
        /// </summary>
        internal static string FirstNumber0_Text {
            get {
                return ResourceManager.GetString("FirstNumber0_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forground color:.
        /// </summary>
        internal static string ForgroundColor_Text {
            get {
                return ResourceManager.GetString("ForgroundColor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forground opacity:.
        /// </summary>
        internal static string ForgroundOpacity_Text {
            get {
                return ResourceManager.GetString("ForgroundOpacity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a format:.
        /// </summary>
        internal static string FormatCode_Text {
            get {
                return ResourceManager.GetString("FormatCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is currently not supported..
        /// </summary>
        internal static string FormatNotSupported_Text {
            get {
                return ResourceManager.GetString("FormatNotSupported_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string FormatTitle_Text {
            get {
                return ResourceManager.GetString("FormatTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string GenerateCode_Text {
            get {
                return ResourceManager.GetString("GenerateCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid start/end character:.
        /// </summary>
        internal static string GuardInvalidStartEnd_Text {
            get {
                return ResourceManager.GetString("GuardInvalidStartEnd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing end character..
        /// </summary>
        internal static string GuardMissingEnd_Text {
            get {
                return ResourceManager.GetString("GuardMissingEnd_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing start character..
        /// </summary>
        internal static string GuardMissingStart_Text {
            get {
                return ResourceManager.GetString("GuardMissingStart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal color codes:
        ///
        ///Characters 1-2: Opacity/Transparency
        ///Characters 3-4: Red
        ///Characters 5-6: Green
        ///Characters 7-8: Blue.
        /// </summary>
        internal static string HexColorCodes_Text {
            get {
                return ResourceManager.GetString("HexColorCodes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language_Text {
            get {
                return ResourceManager.GetString("Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language speech:.
        /// </summary>
        internal static string LanguageSpeech_Text {
            get {
                return ResourceManager.GetString("LanguageSpeech_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the input should be even..
        /// </summary>
        internal static string LengthInputEven_Text {
            get {
                return ResourceManager.GetString("LengthInputEven_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application may be used freely for non-commercial purposes.
        ///Use this program entirely at your own risk..
        /// </summary>
        internal static string License_Text {
            get {
                return ResourceManager.GetString("License_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZXing.Net.Maui by Redth
        ///Barcode scanning and generation for .NET MAUI applications.
        ///MIT License:
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of Barcode Generator (the &apos;Software&apos;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseMit_Text {
            get {
                return ResourceManager.GetString("LicenseMit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The software is provided &apos;as is&apos;, without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the author and/or publisher be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the software or the use or other dealings in the software..
        /// </summary>
        internal static string LicenseMit2_Text {
            get {
                return ResourceManager.GetString("LicenseMit2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string LicenseTitle_Text {
            get {
                return ResourceManager.GetString("LicenseTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode Generator and Scanner.
        /// </summary>
        internal static string NameProgram_Text {
            get {
                return ResourceManager.GetString("NameProgram_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No_Text {
            get {
                return ResourceManager.GetString("No_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this link?.
        /// </summary>
        internal static string OpenLinkText_Text {
            get {
                return ResourceManager.GetString("OpenLinkText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website link.
        /// </summary>
        internal static string OpenLinkTitle_Text {
            get {
                return ResourceManager.GetString("OpenLinkTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No personal and other data is stored or passed on to myself and others..
        /// </summary>
        internal static string PrivacyPolicy_Text {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy:.
        /// </summary>
        internal static string PrivacyPolicyTitle_Text {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will be restarted..
        /// </summary>
        internal static string RestartApp_Text {
            get {
                return ResourceManager.GetString("RestartApp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Text {
            get {
                return ResourceManager.GetString("Settings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string SettingsReset_Text {
            get {
                return ResourceManager.GetString("SettingsReset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SettingsSave_Text {
            get {
                return ResourceManager.GetString("SettingsSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changed settings must be saved in order to apply them..
        /// </summary>
        internal static string SettingsSaved_Text {
            get {
                return ResourceManager.GetString("SettingsSaved_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text contains one or more characters that are not allowed.
        ///
        ///Not allowed:.
        /// </summary>
        internal static string TextContainsChar_Text {
            get {
                return ResourceManager.GetString("TextContainsChar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to encode:.
        /// </summary>
        internal static string TextToEncode_Text {
            get {
                return ResourceManager.GetString("TextToEncode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to speech is not supported on this device..
        /// </summary>
        internal static string TextToSpeechError_Text {
            get {
                return ResourceManager.GetString("TextToSpeechError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        internal static string Theme_Text {
            get {
                return ResourceManager.GetString("Theme_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string ThemeDark_Text {
            get {
                return ResourceManager.GetString("ThemeDark_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string ThemeLight_Text {
            get {
                return ResourceManager.GetString("ThemeLight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string ThemeSystem_Text {
            get {
                return ResourceManager.GetString("ThemeSystem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Version_Text {
            get {
                return ResourceManager.GetString("Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        internal static string Website_Text {
            get {
                return ResourceManager.GetString("Website_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes_Text {
            get {
                return ResourceManager.GetString("Yes_Text", resourceCulture);
            }
        }
    }
}
